### ISSUE TITLE
node:alpine does not work on ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by jarrettone** [jdel/docker-ffrk-proxy#1]
@jdel I don't mind PR-ing this for you, but wanted to get your thoughts on converting this to a more architecture-independent base image so that those of us trying to run this on non-x86 would be able to do so. Thoughts? I was thinking `node:slim`?

Edit: Looks like `node:slim` is Debian-based. Is that concerning for you?

**Comment by jdel** [comment]
Hello @jarrettone 

I can have a look but keeping the image small is required for my use.

I don't mind adding hooks to build an additional ARM image though. 

I am not sure, but I think https://hub.docker.com/r/arm32v7/node/ would be the appropriate base image.

Can you test a local Dockerfile with either `arm32v7/node` or `node:slim` and confirm it works in the raspberry pi ?

**Comment by jarrettone** [comment]
Looks like node:alpine now has ARM images, so this is good now.
